#!/usr/bin/env bash

if [ -z "$1" ]
  then
    echo "The run script takes a command as a argument. E.g., try ./run 'ls' "
    exit 1
fi

set -o noglob
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

COMMAND=$@



container_name=${CONTAINER_NAME:-programming_station}

command -v docker >/dev/null 2>&1 || { echo >&2 "Please install docker. E.g., go to https://www.docker.com/products/docker-desktop "; exit 1; }

docker info >/dev/null 2>&1 || { echo >&2 "Docker server is not running? "; exit 1; }

docker image inspect $container_name >/dev/null 2>&1 || ( echo "instantiating the container" ; docker build -t $container_name -f $SCRIPTPATH/Dockerfile --build-arg USER_ID=$(id -u)  --build-arg GROUP_ID=$(id -g) .  )


docker run  -it --privileged -v $(pwd):/project:Z  $container_name sh -c "$COMMAND"

